### PR TITLE
More option and stuff

### PR DESCRIPTION
**Pull request by Pisti01**
Better "self" display
Other small change

### CODE REVIEW

**Comment by zhevron** [comment]
I had no idea this thing still worked, let alone that it is still being used. I have half a mind to give you contributor access both here and on CurseForge. That's assuming you want it, of course.

Other that that, LGTM. I can't test this as I haven't touched the game for ages, but I'll merge it anyway.

**Comment by Pisti01** [comment]
I didn't do big changes and I tested it through a raid so it should work perfectly.

Also I wouldn't mind contributor access, it would be useful if any error pop up or I decide to do the other few ideas that I have in mind for it.

**Comment by zhevron** [comment]
I've granted you access on Github. If you want it on CurseForge, let me know which username you want me to add.

**Comment by Pisti01** [comment]
My username is: "Amion"

**Pull request merged**
